version: '3.2'
services:
  project-redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  project-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9999:5432"
    volumes:
      - "project_test-db-data:/var/lib/postgresql/data"

volumes:
  project_test-db-data:
