default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database.default.svc.cluster.local
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: deputy-database

test:
  <<: *default
  database: deputy-database

production:
  <<: *default
  database: deputy-database
